# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'windows-latest'

variables:
  project: 'SoftU2FDaemon/*.csproj'
  buildConfiguration: 'Release'

steps:

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '6.x' 
    checkLatest: true # Optional

- task: DotNetCoreInstaller@0
  inputs:
    packageType: 'sdk'
    version: '5.0.404'
    includePreviewVersions: true

- script: dotnet restore
  displayName: Restore packages


- script: dotnet publish
          --configuration Release
          --runtime win10-x64
          --output $(Build.ArtifactStagingDirectory)/win10-x64
          --version-suffix $(Build.BuildNumber)
  displayName: Publish win10-x64 Self-contained deployments (SCD)
  workingDirectory: $(Build.SourcesDirectory)\SoftU2FDaemon

- task: ArchiveFiles@2
  displayName: Archive  win10-x64 Self-contained deployments (SCD)
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/win10-x64'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/SoftU2FDaemon-SCD-win10-x64-$(Build.BuildNumber).zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  displayName: Publish win10-x64-SCD to artifacts
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/SoftU2FDaemon-SCD-win10-x64-$(Build.BuildNumber).zip'
    artifact: 'win10-x64-SCD'
